---
java:
  image: '${IMAGE_NAME}'
  ingressHost: ${SERVICE_FQDN}
  releaseNameOverride: ${RELEASE_NAME}
  environment:
    SERVICES__NOTIFICATIONAPIRESOURCEID: http://vh-test-api.demo.platform.hmcts.net 