# Set variables once
variables:
  solutionType: DotNetCore # angularDotNetCore, dotNetCore, angular
  apiDirectory: "TestApi/TestApi"
  sonarCloudExtraProperties: |
    sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
    sonar.coverage.exclusions=**/TestApi/Program.cs, **/TestApi/Startup.cs, **/TestApi/Extensions/**, **/TestApi/Swagger/**, **/TestApi/ConfigureServicesExtensions.cs, **/Testing.Common/**, **/TestApi.Common/**, **/TestApi.DAL/Mappings/**, **/TestApi.DAL/SeedData/**, **/TestApi.DAL/TestApiDbContext.cs, **/TestApi.DAL/**/DesignTimeHearingsContextFactory.cs, TestApi.DAL/Migrations/**, **/TestApi.Domain/Ddd/**, **/TestApi.DAL/Commands/Core/**, **/TestApi.DAL/Queries/Core/**, **/Testing.Common/**, **/TestApi.DAL/Migrations/*, **/TestApi.DAL/Migrations/**, **/Migrations/*
    sonar.cpd.exclusions="**/Program.cs, **/Startup.cs, TestApi.DAL/Mappings/**, **/TestApi.DAL/Migrations/**, TestApi.DAL/Migrations/**, TestApi.DAL/Migrations/*, TestApi.DAL/Migrations/*.cs, Migrations/**, **/Migrations/*, **Migrations**, SeedData/**, DesignTimeHearingsContextFactory.cs, Ddd/**, Testing.Common/**, TestApi/ConfigureServicesExtensions.cs, TestApi/Extensions/**, TestApi/Swagger/**, TestApi.Common/**"
  coverletCoverageExclusions: "[*]TestApi.Common.*,[*]Testing.Common.*,[TestApi.DAL]TestApi.DAL.TestApiDbContext,[*]TestApi.DAL.Mappings,[*]TestApi.DAL.SeedData.*,[*]TestApi.DAL.Exceptions.*,[*]TestApi.DAL.Mappings.*,[*]TestApi.DAL.Commands.Core.*,[*]TestApi.DAL.Queries.Core.*,[*]TestApi.Domain.Ddd.*,[TestApi.DAL]TestApi.DAL.DesignTimeHearingsContextFactory,[TestApi]TestApi.ConfigureServicesExtensions,[*]TestApi.Extensions.*,[*]TestApi.Swagger.*,[TestApi]TestApi.Program,[TestApi]TestApi.Startup,[*]TestApi.DAL.Migrations.*"
  integrationTestsAppSettingsTransform: '
    "AzureAd/ClientId":"$(vh-admin-web-appid)",
    "AzureAd/ClientSecret":"$(vh-admin-web-key)",
    "AzureAd/TenantId":"$(tenantid)",
    "UsernameStem":"$(username-stem)",
    "Services/TestApiResourceId":"$(vh-TestApi-api-identifieruris)"
    '
  dalWorkingDirectory: "TestApiAPI/TestApi.DAL"
  keyVaultName: vhcoreinfrahtdev # Used to get secrets for integration tests
  secretsFilter: "vh-admin-web-appid,vh-admin-web-key,tenantid,vh-TestApi-api-identifieruris" # filters out secrets returned from key vault

# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
    - repository: azureDevOpsTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master # ref name to use, defaults to 'refs/heads/master'
      endpoint: hmcts

trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*
pr:
  - master

jobs:
  - template: jobs/efMigration.yml@azureDevOpsTemplates # Template reference
    parameters:
      dbProjectPath: $(Build.SourcesDirectory)/TestApiAPI/TestApi.DAL/TestApi.DAL.csproj
      pool: Azure-VSTS-VS2017

  - template: jobs/angularDotNetCore.yml@azureDevOpsTemplates # Template reference
    parameters:
      sonarCloudExtraProperties: $(sonarCloudExtraProperties)
      integrationTestsAppSettingsTransform: $(integrationTestsAppSettingsTransform)
      coverletCoverageExclusions: $(coverletCoverageExclusions)
      apiDirectory: $(apiDirectory)
      dalWorkingDirectory: $(dalWorkingDirectory)
      keyVaultName: $(keyVaultName)
      secretsFilter: $(secretsFilter)
      dotNetCoreVersion: '3.1.100'
