version: '3.4'

services:
  testapi:
    container_name: testapi
    restart: always
    image: ${DOCKER_REGISTRY-}testapi
    build:
      context: .
      dockerfile: TestApi/Dockerfile
    depends_on:
      - "db"
    environment:
      SQLCONNSTR_TestApi: 'Server=db;Database=TestApi;User ID=sa;Password=VeryStrongPassword!;'

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    expose:
      - "1433"
    environment:
      ACCEPT_EULA: 'yes'
      SA_PASSWORD: 'VeryStrongPassword!'